config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'

  get 'mywords', to: 'groups#api'
  post 'fork', :to => 'groups#createano'
  post 'indexuser', :to => 'groups#indexuser'

  namespace :account do
    resources :groups
    resources :posts
    resources :askwords
  end

  resources :groups do
    member do
      post :join
      post :quit
      post :fork
      get :fork
      patch :fork
      post :indexuser
      get :indexuser
      patch :indexuser
    end
    resources :posts
  end
  resources :askwords

end

app/models/group.rb
class Group < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :recent, -> { order("updated_at DESC") }
  scope :posts_count_D, -> { order("posts_count DESC") }

  validates :title, presence: true, length: { maximum: 20 }

  has_many :posts, dependent: :destroy
  has_many :group_users
  has_many :members, through: :group_users, source: :user

  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == owner
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups.order("posts_count DESC")
  end
end

app/controllers/groups_controller.rb
# == schema information
# table name groups
#  id             :integer    not null, primary key
#  titile         :string     default(""), not null
#  description    :text       default(""), not null
#  font           :string     default(""), not null
#  created_at     :datetime   not null
#  updated_at     :datetime   not null

class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :find_group, only: [:show, :edit, :update, :join, :quit, :fork]
  before_action :find_group_current_user, only: [:edit, :update, :destroy]

  def api
    groups = Group.all
    render json: groups
  end

  def index
    @groups = Group.all.recent
    @groups = @groups.page(params[:page]).per(7)
  end

  def indexuser
    @groups = Group.where(owner: params[:group_owner]).recent
    @groups = @groups.page(params[:page]).per(7)
  end

  def new
    @group = Group.new
  end

  def show
    @posts = @group.posts.recent
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: '造字更新成功'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, alert: '造字已煙消雲散'
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      current_user.join!(@group)
      # UserMailer.notify_comment(current_user, @group.title).deliver_now!
      redirect_to groups_path, notice: '造字已召告天下!'
    else
      render :new
    end
  end

  # fork功能，可發展別人的字
  def createano
    if current_user
      @group = current_user.groups.new(group_params)
      current_user.join!(@group)
    else
      @group = Group.new(group_params)
    end
    if @group.save
      redirect_to groups_path, notice: '舊字已新告天下!'
    else
      render :fork
    end
  end

  def fork
  end

  def join
    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = '你已開始信此字'
    else
      flash[:warning] = '你早已是此字信眾'
    end
    redirect_to group_path(@group)
  end

  def quit
    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = '你已不信此字'
    else
      flash[:warning] = '你不是本字信眾'
    end
    redirect_to group_path(@group)
  end

  private

  def find_group
    @group = Group.friendly.find(params[:id])
  end

  def find_group_current_user
    @group = current_user.groups.friendly.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:title, :description, :font, :slug)
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_title(group)
    truncate(group.title, length: 10)
  end
  def render_group_description(group)
    truncate(group.description, length: 10)
  end
end

app/views/groups/_form.html.haml
= simple_form_for @group do |f| 
  = render "formgroup", :f => f
  = f.submit "送出", class: "btn btn-primary", data: { disable_with: "送出中..." }

app/views/groups/_formgroup.html.haml
.form-group
  = f.input :title, autofocus: true, hint: '使用⿰左右,⿱上下,⿴包圍，將兩個字組合，例如：⿰⼸長=張, ⿴囗或=國, ⿱⾅男=舅', placeholder: '⿰⼸長'
  = f.input :description, id: "wordwhy",  placeholder: '說說看這字啥意思唄'
  = f.collection_radio_buttons :font, [['宋體', '【宋體】'] ,['楷體', '【楷體】'] ,['宋體粗體', '【宋體粗體】'] ,['楷體粗體', '【楷體粗體】']], :first, :last

app/views/groups/_wordref.html.haml
%h3= "組合字元： ⿰⿱⿴"
%p= "鍵盤開發中，請複製貼上至組合碼欄 😀  😃  😄  😊  😁  😆"
%h2= "參考字元"
%h3= "⼀ ⼁ ⼂ ⼃ ⼄ ⼅ ⼆ ⼇ ⼈ ⼉ ⼊ ⼋ ⼌ ⼍ ⼎ ⼏ ⼐ ⼑ ⼒ ⼓ ⼔ ⼕ ⼖ ⼗ ⼘ ⼙ ⼚ ⼛ ⼜ ⼝ 囗 ⼟ ⼠ ⼡ ⼢ ⼣ ⼤ ⼥ ⼦ ⼧ ⼨ ⼩ ⼪ ⼫ ⼬ ⼭ ⼮ ⼯ ⼰ ⼱ ⼲ ⼳ ⼴ ⼵ ⼶ ⼷ ⼸ ⼹ ⼺ ⼻ ⼼ ⼽ ⼾ ⼿ ⽀ ⽁ ⽂ ⽃ ⽄ ⽅ ⽆ ⽇ ⽈ ⽉ ⽊ ⽋ ⽌ ⽍ ⽎ ⽏ ⽐ ⽑ ⽒ ⽓ ⽔ ⽕ ⽖ ⽗ ⽘ ⽙ ⽚ ⽛ ⽜ ⽝ ⽞ ⽟ ⽠ ⽡ ⽢ ⽣ ⽤ ⽥ ⽦ ⽧ ⽨ ⽩ ⽪ ⽫ ⽬ ⽭ ⽮ ⽯ ⽰ ⽱ ⽲ ⽳ ⽴ ⽵ ⽶ ⽷ ⽸ ⽹ ⽺ ⽻ ⽼ ⽽ ⽾ ⽿ ⾀ ⾁ ⾂ ⾃ ⾄ ⾅ ⾆ ⾇ ⾈ ⾉ ⾊ ⾋ ⾌ ⾍ ⾎ ⾏ ⾐ ⾑ ⾒ ⾓ ⾔ ⾕ ⾖ ⾗ ⾘"
-# %h2= "簡體部首"
-# %h3= "⺀ ⺁ ⺂ ⺃ ⺄ ⺅ ⺆ ⺇ ⺈ ⺉ ⺊ ⺋ ⺌ ⺍ ⺎ ⺏ ⺐ ⺑ ⺒ ⺓ ⺔ ⺕ ⺖ ⺗ ⺘ ⺙ ⺛ ⺜ ⺝ ⺞ ⺟ ⺠ ⺡ ⺢ ⺣ ⺤ ⺥ ⺦ ⺧ ⺨ ⺩ ⺪ ⺫ ⺬ ⺭ ⺮ ⺯ ⺰ ⺱ ⺲ ⺳ ⺴ ⺵ ⺶ ⺷ ⺸ ⺹ ⺺ ⺻ ⺼ ⺽ ⺾ ⺿ ⻀ ⻁ ⻂ ⻃ ⻄ ⻅ ⻆ ⻇ ⻈ ⻉ ⻊ ⻋ ⻌ ⻍ ⻎ ⻏ ⻐ ⻑ ⻒ ⻓ ⻔ ⻕ ⻖ ⻗ ⻘ ⻙ ⻚ ⻛ ⻜ ⻝ ⻞ ⻟ ⻠ ⻡ ⻢ ⻣ ⻤ ⻥ ⻦ ⻧ ⻨ ⻩ ⻪ ⻫ ⻬ ⻭ ⻮ ⻯ ⻰ ⻱ ⻲ ⻳"
-# %h2= "其它"
-# %h3= "𦥯"

app/views/groups/edit.html.haml
.col-md-4.col-md-offset-4
  %h1 字造。改
  %hr
  = render "form", group: @group
  = render "wordref"
  -# = react_component "線上組字"

app/views/groups/fork.html.haml
.col-md-4.col-md-offset-4
  %h1 字造。再造
  %hr
  = simple_form_for @group, :url => { :controller => 'groups', :action => 'createano' }, :method => :POST do |f|
    = render "formgroup", :f => f
    = f.submit "送出", class: "btn btn-primary", data: { disable_with: "送出中..." }
  = render "wordref"

app/views/groups/index.html.erb
<div>
  <div id="masonry-container" class="transitions-enabled centered clearfix masonry">
    <% @groups.each do |group| %>
      <div class="box col2" align="center" >
        <%= link_to(
        image_tag("https://tools.wmflabs.org/idsgen/#{group.title}.png?字體=宋體粗體", size: "100", alt: group.title, class: "img-responsive"
        ), group_path(group))%>
        <p>
          <!-- <%= render_group_description(group) %> -->
          <!-- <%= link_to(render_group_title(group), group_path(group)) %> -->
          <!-- <%= group.posts.size %> -->
          <!-- <%= group.updated_at.to_s(:short)  %> -->
        </p>
      </div>
    <% end %>
  </div>
  <div align="center">
    <%= render "common/mainfunction" %>
    <%= react_component "WorldOnline" %>
    <%= paginate @groups, :theme => 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/groups/indexuser.html.erb
<div>
  <div id="masonry-container" class="transitions-enabled centered clearfix masonry">

    <% @groups.each do |group| %>
      <div class="box col2" align="center" >
        <%= link_to(
        image_tag("https://tools.wmflabs.org/idsgen/#{group.title}.png?字體=宋體粗體", size: "100", alt: group.title, class: "img-responsive"
        ), group_path(group))%>
        <p>
          <!-- <%= render_group_description(group) %> -->
          <!-- <%= link_to(render_group_title(group), group_path(group)) %> -->
          <!-- <%= group.posts.size %> -->
          <!-- <%= group.updated_at.to_s(:short)  %> -->
        </p>
      </div>
    <% end %>
  </div>
  <div align="center">
    <%= render "common/mainfunction" %>
    <%= react_component "WorldOnline" %>
    <%= paginate @groups, :theme => 'twitter-bootstrap-3' %>
  </div>
</div>

app/views/groups/new.html.haml
.col-md-4.col-md-offset-4
  %h1= "字造。新"
  = render "form", group: @group
  = render "wordref"

app/views/groups/show.html.erb
<div class="col-md-4 col-md-offset-4">
  <div align="center"><%= content_tag(:a , image_tag("https://tools.wmflabs.org/idsgen/#{@group.title}.png?字體=#{@group.font}", size: "250", alt: @group.title),:href => "https://tools.wmflabs.org/idsgen/#{@group.title}.svg?字體=#{@group.font}" ,:download =>"" ) %></div>
  <br />
  <div class="group" align="center">
    <% if @group.editable_by?(current_user) %>
      <!-- <%= link_to("解字。新", new_group_post_path(@group), class: "btn btn-success") %> -->
      <%= link_to("📝 字修改", edit_group_path(@group), class: "btn btn-warning")%>
    <% end %>
    <%= link_to("🔄 字再創", fork_group_path(@group), class: "btn btn-info")%>
    <!-- <% if current_user.present? %>
      <% if current_user.is_member_of?(@group) %>
        <%= link_to("不採", quit_group_path(@group), method: :post, class: "btn btn-danger") %>
      <% else %>
        <%= link_to("採", join_group_path(@group), method: :post, class: "btn btn-info") %>
      <% end %>
    <% end %> -->
  </div>
  <br />
  <h4>【文字組合碼】<%= @group.title %></h4>
  <h4>【字型】<%= @group.font %></h4>
  <h4>【創作者】<%= link_to( @group.owner ? @group.owner.name : "路人甲", indexuser_group_path(@group, :group_owner => @group.owner) ) %></h4>
  <p><%= simple_format(@group.description) %></p>
  <!-- <table class="table table-responsive">
   <thead>
     <tr>
       <th>解字</th>
       <th colspan="2"></th>
     </tr>
   </thead>
   <tbody>
     <% @posts.each do |post| %>
       <tr>
         <td><%= render_post_content(post) %></td>
         <td>
           <% if @group.editable_by?(current_user) %>
             <td align="right">
               <%= link_to('改', edit_group_post_path(post.group, post), class: "btn btn-info btn-xs") %>
               <%= link_to('滅', group_post_path(post.group, post), method: :delete, data: { confirm: "解字消滅?" }, class: "btn btn-danger btn-xs") %>
             </td>
           <% end %>
         </td>
       </tr>
     <% end %>
   </tbody>
  </table> -->
  <!-- <%= social_share_button_tag(@group.title, :popup => "true", :url => request.original_url, :image => "https://tools.wmflabs.org/idsgen/#{@group.title}.png?字體=宋體") %> -->
  <%= render 'disqus' %>
</div>