config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'

  get 'mywords', to: 'groups#api'
  post 'fork', :to => 'groups#createano'
  post 'indexuser', :to => 'groups#indexuser'

  namespace :account do
    resources :groups
    resources :posts
    resources :askwords
  end

  resources :groups do
    member do
      post :join
      post :quit
      post :fork
      get :fork
      patch :fork
      post :indexuser
      get :indexuser
      patch :indexuser
    end
    resources :posts
  end
  resources :askwords

end

app/models/askword.rb
class Askword < ActiveRecord::Base
  scope :recent, -> { order("updated_at DESC") }

  validates :title, presence: true, length: { maximum: 20 }

  has_many :askword_users
  has_many :members, through: :askword_users, source: :user

  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == owner
  end

end

app/controllers/askwords_controller.rb
class AskwordsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :find_askword, only: [:show, :edit, :update]
  before_action :find_askword_current_user, only: [:edit, :update, :destroy]


  def index
    @askwords = Askword.all.recent
  end

  def new
    @askword = Askword.new
  end

  # def show
  #   @posts = @askword.posts.recent
  # end

  def edit
  end

  def update
    if @askword.update(askword_params)
      redirect_to askwords_path, notice: "求字更新成功"
    else
      render :edit
    end
  end

  def destroy
    @askword.destroy
    redirect_to askwords_path, alert: "已取消求字"
  end

  def create
    @askword = current_user.askwords.new(askword_params)

    if @askword.save
      redirect_to askwords_path, notice: "求字已召告天下!"
    else
      render :new
    end
  end

  private
  def find_askword
    @askword = Askword.find(params[:id])
  end

  def find_askword_current_user
    @askword = current_user.askwords.find(params[:id])
  end

  def askword_params
    params.require(:askword).permit(:title, :description)
  end
end

app/helpers/askwords_helper.rb
module AskwordsHelper
  def render_askword_title(askword)
    truncate(askword.title, length: 10)
  end
  def render_askword_description(askword)
    truncate(askword.description, length: 10)
  end
end

app/views/askwords/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//ctaiwan.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/askwords/_form.html.haml
= simple_form_for @askword do |f|
  .form-askword
    = f.input :title, autofocus: true
    = f.input :description
  = f.submit "送出", class: "btn btn-primary", data: { disable_with: "送出中..." }

app/views/askwords/edit.html.haml
.col-md-4.col-md-offset-4
  %h1 求字。改
  %hr
  = render "form", askword: @askword

app/views/askwords/index.html.erb
<div class="col-md-12">
  <br>
  <!-- <img src="https://tools.wmflabs.org/idsgen/⿺辶⿴宀⿱珤⿰隹⿰貝招.png?字體=宋體" type="image/svg+xml" style="height: 150px; width: 150px; " /> -->
  <div id="masonry-container" class="transitions-enabled fluid">
    <br>
    <% @askwords.each do |askword| %>
      <div class="box" align="center">
        <p>
          <h2><%= link_to(render_askword_title(askword), askword_path(askword)) %></h2>
          <%= render_askword_description(askword) %>
          <br/>
          <%= askword.updated_at.to_s(:short)  %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/askwords/new.html.haml
.col-md-4.col-md-offset-4
  %h1= "求字。新"
  = render "form", askword: @askword

app/views/askwords/show.html.haml
.col-md-4.col-md-offset-4
  .askword
    -# -if @askword.editable_by?(current_user)
    -#   = link_to("求字。改", edit_askword_path(@askword), class: "btn btn-primary pull-right")
    -#   = link_to("求字。滅", askword_path(@askword), class: "btn btn-primary btn-danger pull-right", method: :delete, data: { confirm: "求字刪去?" } )
  %br
  %h2= @askword.title
  %p= simple_format(@askword.description)
  %br
  -# = social_share_button_tag(@askword.title, :popup => "true", :url => request.original_url, :image => "https://tools.wmflabs.org/idsgen/#{@askword.title}.png?字體=宋體")
  = render 'disqus'
</div>