config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'

  get 'mywords', to: 'groups#api'
  post 'fork', :to => 'groups#createano'
  post 'indexuser', :to => 'groups#indexuser'

  namespace :account do
    resources :groups
    resources :posts
    resources :askwords
  end

  resources :groups do
    member do
      post :join
      post :quit
      post :fork
      get :fork
      patch :fork
      post :indexuser
      get :indexuser
      patch :indexuser
    end
    resources :posts
  end
  resources :askwords

end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 20px;">
  <p class="text-center">2016 <a href="http://j.mp/ctaiwan" target=_new>cTaiwan</a>
    <!-- <%= link_to "中文", :controller => controller_name, :action => action_name, :locale => "zh-TW" %>
    <%= "|" %>
    <%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %> -->
  </p>
  <p class="text-center">
    <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fsheltered-oasis-97791.herokuapp.com%2F&width=450&layout=standard&action=like&size=large&show_faces=true&share=true&height=80&appId=1634750370172049" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
  </p>
</footer>

app/views/common/_mainfunction.html.erb
<div>
  <% if current_user %>
    <%= link_to("🆕 新字造", new_group_path, class: "btn btn-primary btn-lg") %>
  <% end %>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <div>
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><img alt="字造者" src="https://tools.wmflabs.org/idsgen/⿱⿱臼大心.png?字體=宋體" style="height: 20px; width: 20px; " /></a>
    </div>
    <div>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li> <%= link_to("註冊", new_user_registration_path) %> </li>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li><%= link_to("待造區", askwords_path) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              字造吧!「 <%= current_user.name %> 」
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("求造字", new_askword_path) %></li>
              <li> <%= link_to("我的造字", account_groups_path) %></li>
              <!-- <li><%= link_to("我的追字", askwords_path) %></li> -->
              <!-- <li> <%= link_to("我的解字", account_posts_path) %></li> -->
              <li> <%= link_to("改頭換面", edit_user_registration_path) %></li>
              <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_search.html.erb
<%= form_tag(groups_path, :method => "get", id: "search-form", role: "search", class: "navbar-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "字根找字", class: "form-control", :autofocus=>true %>
    <%= submit_tag "找", :name => nil, class: "btn btn-default" %>
<% end %>